/**
 * Demo dataset for Sunset Ridge Tanning, August 2026.
 * No audio is processed anywhere in this codebase.
 * Customers are pattern labels, never names.
 */
import type { MonitorFixture } from './types';

export const DEMO_MONITOR: MonitorFixture = {
  status: {
    deviceName: 'Front Desk Listener',
    location: 'Front desk',
    online: true,
    interactionsToday: 47,
    uptimeDays: 12,
    consentNote:
      'The team knows it\'s here. Conversations are scored for coaching — nobody is disciplined off a transcript.',
  },
  interactions: [
    {
      id: 'int-01',
      time: '10:05 AM',
      employee: 'Maya',
      customerLabel: 'Regular · visits 2×/week',
      excerpt: [
        { speaker: 'staff', text: 'Hi there! Welcome back to Sunset Ridge.' },
        { speaker: 'customer', text: 'Hi, I\'m just here for a spray tan.' },
        { speaker: 'staff', text: 'Great! We have the classic spray tan and the express 20-minute option.' },
        { speaker: 'customer', text: 'I\'ll take the classic one. How much is membership again?' },
        { speaker: 'staff', text: 'It\'s $149 for 10 visits, so that\'s $14.90 per visit. That\'s a great deal if you\'re coming often.' },
        { speaker: 'customer', text: 'That sounds good, I\'ll take it!' },
      ],
      scores: {
        greeting: 5,
        needs: 5,
        product: 4,
        membership: 5,
        close: 5,
      },
      outcome: 'membership',
      outcomeDetail: 'Signed up for classic membership',
      coachingNote: 'Great job doing the per-visit math out loud — this helped convert the customer.',
    },
    {
      id: 'int-02',
      time: '11:15 AM',
      employee: 'Jordan',
      customerLabel: 'New · first visit',
      excerpt: [
        { speaker: 'staff', text: 'Hi, welcome to Sunset Ridge! What can I help you with today?' },
        { speaker: 'customer', text: 'I\'m looking for a spray tan.' },
        { speaker: 'staff', text: 'Great! We have several options. Are you looking for a classic or express tan?' },
        { speaker: 'customer', text: 'I\'d like the classic one, but I was wondering about the products they use.' },
        { speaker: 'staff', text: 'We use a premium moisturizing spray that helps with skin hydration.' },
        { speaker: 'customer', text: 'That sounds good. Is there anything else you can tell me about it?' },
        { speaker: 'staff', text: 'I\'ll have to check the product details for you, but I can show you the brochure.' },
      ],
      scores: {
        greeting: 5,
        needs: 4,
        product: 0,
        membership: 0,
        close: 3,
      },
      outcome: 'missed_opportunity',
      outcomeDetail: 'Customer mentioned skin care but no product details provided',
      coachingNote: 'When customers bring up skin care, be ready to mention the products you use.',
    },
    {
      id: 'int-03',
      time: '2:30 PM',
      employee: 'Priya',
      customerLabel: 'Member · 8 months',
      excerpt: [
        { speaker: 'staff', text: 'Hello, welcome back! How are you doing today?' },
        { speaker: 'customer', text: 'I\'m good, thanks! I was just here for a spray tan.' },
        { speaker: 'staff', text: 'Great! Are you interested in trying our new express option?' },
        { speaker: 'customer', text: 'That sounds interesting. How much does it cost?' },
        { speaker: 'staff', text: 'It\'s $25 for 10 minutes, but I need to check with the manager.' },
        { speaker: 'customer', text: 'Okay, that\'s fine. I\'ll take the classic one.' },
      ],
      scores: {
        greeting: 5,
        needs: 4,
        product: 3,
        membership: 1,
        close: 3,
      },
      outcome: 'no_sale',
      outcomeDetail: 'Did not mention membership options',
      coachingNote: 'As a new team member, remember to offer membership options when customers inquire about services.',
    },
    {
      id: 'int-04',
      time: '3:45 PM',
      employee: 'Maya',
      customerLabel: 'Lapsed · last visit 6 weeks ago',
      excerpt: [
        { speaker: 'staff', text: 'Hi there, welcome back!' },
        { speaker: 'customer', text: 'Hello, I was just here for a spray tan.' },
        { speaker: 'staff', text: 'Great! How are you doing today?' },
        { speaker: 'customer', text: 'I\'m good. I haven\'t been here in a while, but I heard about your new products.' },
        { speaker: 'staff', text: 'We have some great new moisturizing sprays that really help with skin hydration.' },
        { speaker: 'customer', text: 'That sounds great, what do they contain?' },
        { speaker: 'staff', text: 'They contain aloe vera and hyaluronic acid for deep hydration.' },
      ],
      scores: {
        greeting: 4,
        needs: 5,
        product: 5,
        membership: 3,
        close: 4,
      },
      outcome: 'missed_opportunity',
      outcomeDetail: 'Customer returned after gap but no welcome or re-engagement',
      coachingNote: 'When customers return after a gap, acknowledge their return and show genuine interest in their experience.',
    },
    {
      id: 'int-05',
      time: '4:20 PM',
      employee: 'Jordan',
      customerLabel: 'Regular · visits 2×/week',
      excerpt: [
        { speaker: 'staff', text: 'Hi there, welcome back! What can I help you with today?' },
        { speaker: 'customer', text: 'I just need a classic spray tan.' },
        { speaker: 'staff', text: 'Great! Would you like to try our new express option for 10 minutes?' },
        { speaker: 'customer', text: 'That sounds interesting, but I\'m not sure.' },
        { speaker: 'staff', text: 'I can show you the brochure if you want more details.' },
        { speaker: 'customer', text: 'No thanks, I\'ll stick with the classic one.' },
      ],
      scores: {
        greeting: 5,
        needs: 4,
        product: 3,
        membership: 0,
        close: 2,
      },
      outcome: 'no_sale',
      outcomeDetail: 'Did not mention membership options',
      coachingNote: 'Even when customers decline, always consider offering membership options as part of the closing process.',
    },
    {
      id: 'int-06',
      time: '5:15 PM',
      employee: 'Priya',
      customerLabel: 'New · first visit',
      excerpt: [
        { speaker: 'staff', text: 'Welcome to Sunset Ridge! How can I help you today?' },
        { speaker: 'customer', text: 'I\'m looking for a spray tan and some advice on skin care.' },
        { speaker: 'staff', text: 'Great! We have several options that work well for dry skin.' },
        { speaker: 'customer', text: 'That sounds perfect. What products do you use?' },
        { speaker: 'staff', text: 'We use premium moisturizing sprays, but I\'ll have to check with my manager about specific details.' },
        { speaker: 'customer', text: 'Okay, that\'s fine.' },
      ],
      scores: {
        greeting: 5,
        needs: 4,
        product: 0,
        membership: 2,
        close: 3,
      },
      outcome: 'missed_opportunity',
      outcomeDetail: 'Customer asked about products but no details provided',
      coachingNote: 'When customers ask about products, be prepared to provide specific information or direct them to more information.',
    },
    {
      id: 'int-07',
      time: '6:10 PM',
      employee: 'Maya',
      customerLabel: 'Member · 8 months',
      excerpt: [
        { speaker: 'staff', text: 'Hi there, welcome back! How are you doing today?' },
        { speaker: 'customer', text: 'I\'m good, thanks! Just here for a spray tan.' },
        { speaker: 'staff', text: 'Great! Would you like to try our new express option?' },
        { speaker: 'customer', text: 'That sounds interesting. How much is it?' },
        { speaker: 'staff', text: 'It\'s $25 for 10 minutes, but that\'s a great deal if you\'re coming often.' },
        { speaker: 'customer', text: 'That\'s good to know, I might try it next time.' },
      ],
      scores: {
        greeting: 5,
        needs: 4,
        product: 4,
        membership: 4,
        close: 5,
      },
      outcome: 'sale',
      outcomeDetail: 'Customer expressed interest in new option',
      coachingNote: 'Good job of explaining the value proposition when offering new options.',
    },
    {
      id: 'int-08',
      time: '6:40 PM',
      employee: 'Jordan',
      customerLabel: 'Lapsed · last visit 6 weeks ago',
      excerpt: [
        { speaker: 'staff', text: 'Hi there, welcome back!' },
        { speaker: 'customer', text: 'Hello! I\'m just here for a spray tan.' },
        { speaker: 'staff', text: 'Great! How are you doing today?' },
        { speaker: 'customer', text: 'I\'m good. I haven\'t been here in a while.' },
        { speaker: 'staff', text: 'We\'re happy to see you back!' },
        { speaker: 'customer', text: 'Thank you, I\'ve been meaning to come back.' },
      ],
      scores: {
        greeting: 3,
        needs: 4,
        product: 3,
        membership: 0,
        close: 2,
      },
      outcome: 'missed_opportunity',
      outcomeDetail: 'Customer returned after gap but no welcome or re-engagement',
      coachingNote: 'When customers return after a gap, acknowledge their return and show genuine interest in their experience.',
    },
  ],
  employees: [
    {
      name: 'Maya',
      role: 'Front desk',
      interactions: 18,
      membershipMentions: 9,
      conversions: 4,
      attachmentPct: 31,
      trend: 'up',
      flag: undefined,
    },
    {
      name: 'Jordan',
      role: 'Evenings',
      interactions: 14,
      membershipMentions: 2,
      conversions: 0,
      attachmentPct: 9,
      trend: 'down',
      flag: 'Product moments — pair with Maya this week',
    },
    {
      name: 'Priya',
      role: 'Part-time',
      interactions: 9,
      membershipMentions: 1,
      conversions: 0,
      attachmentPct: 18,
      trend: 'flat',
      flag: 'New — membership answers, not effort',
    },
    {
      name: 'Tess',
      role: 'Manager',
      interactions: 6,
      membershipMentions: 3,
      conversions: 1,
      attachmentPct: 24,
      trend: 'flat',
      flag: undefined,
    },
  ],
  insights: [
    {
      id: 'mi-01',
      pattern: 'Evening shift rarely mentions products after 6 PM even when customers bring up skin care.',
      evidenceCount: 11,
      suggestion: 'A two-minute shift-start habit — one featured lotion, one sentence about it.',
      knowledgeRef: 'Room A · 10:42',
    },
    {
      id: 'mi-02',
      pattern: 'When staff do the per-visit membership math out loud, customers say yes far more often (Maya\'s method).',
      evidenceCount: 9,
      suggestion: 'Make the math the standard answer to "how much is membership?"',
      knowledgeRef: 'Room B · 2:17',
    },
    {
      id: 'mi-03',
      pattern: 'Returning lapsed customers are greeted like strangers — nobody welcomes them back.',
      evidenceCount: 5,
      suggestion: 'Check-in flags the gap so the greeting can land; no knowledgeRef.',
    },
  ],
};